--- 
jobs: 
  build: 
    docker: 
      - 
        auth: 
          password: $DOCKERHUB_PASSWORD
          username: xaela37
        image: "cimg/node:14.15.0"
    steps: 
      - checkout
      - 
        run: "yarn install"
      - 
        save_cache: 
          key: "npm-v1-dependencies-{{ checksum \"yarn.lock\" }}"
          paths: 
            - node_modules
  end_to_end: 
    docker: 
      - 
        auth: 
          password: $DOCKERHUB_PASSWORD
          username: xaela37
        image: "cimg/node:14.15.0"
      - 
        auth: 
          password: $DOCKERHUB_PASSWORD
          username: xaela37
        environment: 
          POSTGRES_DB: pgdb
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: pguser
        image: "circleci/postgres:9.6.2-alpine"
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "npm-v1-dependencies-{{ checksum \"yarn.lock\" }}"
      - 
        run: 
          command: "yarn test:e2e"
          environment: 
            DATABASE_URL: "postgres://pguser:pass@localhost:5432/pgdb"
          name: "yarn test"
  lint: 
    docker: 
      - 
        auth: 
          password: $DOCKERHUB_PASSWORD
          username: xaela37
        image: "cimg/node:14.15.0"
    steps: 
      - checkout
      - 
        restore_cache: 
          key: "npm-v1-dependencies-{{ checksum \"yarn.lock\" }}"
      - 
        run: 
          command: |-
              yarn lint
              yarn format:check
          name: "step lint"
  test_unit: 
    docker: 
      - 
        auth: 
          password: $DOCKERHUB_PASSWORD
          username: xaela37
        image: "cimg/node:14.15.0"
      - 
        auth: 
          password: $DOCKERHUB_PASSWORD
          username: xaela37
        environment: 
          POSTGRES_DB: pgdb
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: pguser
        image: "circleci/postgres:9.6.2-alpine"
    steps: 
      - checkout
      - 
        restore_cache: 
          key: "npm-v1-dependencies-{{ checksum \"yarn.lock\" }}"
      - 
        run: 
          command: "yarn test"
          environment: 
            DATABASE_URL: "postgres://psqluer:psqlpassword@localhost:5432/psqluer"
version: 2
workflows: 
  my_workflow: 
    jobs: 
      - build
      - 
        test_unit: 
          requires: 
            - build
      - 
        end_to_end: 
          requires: 
            - build
      - 
        lint: 
          requires: 
            - build
  version: 2
